:: Author: lokkelvin2
:: Created: 2023-08-11
::
:: This program queries netstat and returns the localhost port numbers that are active.
:: Explanations are generated by GPT-3.5

:: Explanations
::netstat: This is the command itself. When executed, it provides information about network connections.
:: -n: This option stands for "numeric." When used with the netstat command, it prevents netstat from attempting to resolve IP addresses and port numbers to hostnames and service names. Instead, it displays numeric IP addresses and port numbers. This can be helpful in cases where hostname resolution might be slow or unnecessary.
:: >netstat -n
:: 
:: Active Connections
:: 
::  Proto  Local Address          Foreign Address        State
::  TCP    127.0.0.1:1924         127.0.0.1:5354         ESTABLISHED
::  TCP    127.0.0.1:1925         127.0.0.1:1926         ESTABLISHED

::Here's a breakdown of each component in the command:
::
:: for /f: This initiates a loop using the /f option, which is used to process text (usually lines of output from a command or file).
:: 
:: "tokens=3 delims=: ": This part specifies the behavior of the loop. The tokens=3 means that you're interested in the third part (token) of each line. The delims=: indicates that the line should be split into tokens based on the colon (:) character. Additionally, space characters are included in the delimiters, so they are treated as separators too.
:: 
:: %%a: This is a loop variable that represents the value of the current token being processed. In batch scripts, you use %%a when running the loop in a batch file. If you were running this command directly in the Command Prompt, you would use %a instead.
:: 
:: 'netstat -n ^| findstr 127.0.0.1': This is the command that generates the input for the loop. It first runs netstat -n to get network information (with numeric addresses), then pipes (|) the output to findstr to filter lines containing 127.0.0.1 (localhost).
:: 
:: do @echo %%a: This specifies the action to be performed for each iteration of the loop. In this case, it prints the value of the loop variable (%%a or %a) using the echo command.
:: 
:: Putting it all together, the command processes the output of netstat -n | findstr 127.0.0.1 line by line. For each line, it splits the line into tokens using : and space as delimiters. The third token, representing the port number, is then printed using the echo command.
:: 
:: This command essentially extracts and prints the port numbers from the lines of netstat output that contain 127.0.0.1.

:: For batch script, use %%a to escape the first %
for /f "tokens=3 delims=: " %%a in ('netstat -n ^| findstr 127.0.0.1') do @echo %%a

:: For cmdline, use %a which represents loop variables
:: for /f "tokens=3 delims=: " %a in ('netstat -n ^| findstr 127.0.0.1') do @echo %a